### ISSUE TITLE
Forbidden resource

### ISSUE THREAD

**Issue by mehdimoozeh** [stamer/texmlbus#61]
When I click on `queue` (xhtml) I will receive 403 forbidden on  `/api/rerun`.
What should I do?

**Comment by stamer** [comment]
Hi, please let me know a little bit more about your setup. Are you using texmlbus inside wsl2?
Are you able to create the samples and convert them to xhtml?
For security reasons access is  limited to 127.0.0.1 (which is the localhost). You can try and replace 
the line 93 and 94 in `docker-compose.yml` so they read (removing the limitation to 127.0.0.1)
```
            - "${TEXMLBUS_HTTP:-8080}:80"
            - "${TEXMLBUS_HTTPS:-8443}:443"
```
and the run `docker-compose up` again.
There is `docker/tools/webserver-log` (for access bia `http://localhost`) oder `docker/tools/webserver-ssl-log` (for access via `https::/localhost`), as well es `worker-log`. Do they give you any messages when you run them and then try to queue a document?

**Comment by stamer** [comment]
Issue has been checked again and cannot be reproduced.
Closed, because no further details followed.
